module BcubeTutorialsTests
using Pkg
using Test

const TEST_DIR = joinpath(@__DIR__)
const UTILS_PATH = joinpath(TEST_DIR, "utils.jl")
const REMOVE_TMP_FILES = true

function print_centered_with_hash(s::String, n::Int)
    @assert n > 4 + length(s)

    total_padding = n - 4 - length(s)
    left_padding = div(total_padding, 2)
    right_padding = total_padding - left_padding

    centered = "##" * " "^left_padding * s * " "^right_padding * "##"

    println(repeat("#", n))
    println(repeat("#", n))
    println("##" * " "^(n - 4) * "##")
    println(centered)
    println("##" * " "^(n - 4) * "##")
    println(repeat("#", n))
    println(repeat("#", n))
end

Pkg.activate(TEST_DIR)
Pkg.instantiate()

has_custom_bcube_branch =
    haskey(ENV, "BCUBE_BRANCH") && !isempty(strip(ENV["BCUBE_BRANCH"]))
custom_bcube_branch = if has_custom_bcube_branch
    branch = strip(get(ENV, "BCUBE_BRANCH", "main"))
    @info "Running tests with custom Bcube branch '$branch'"
    branch
else
    nothing
end
has_custom_bcubevtk_branch =
    haskey(ENV, "BCUBEVTK_BRANCH") && !isempty(strip(ENV["BCUBEVTK_BRANCH"]))
custom_bcubevtk_branch = if has_custom_bcubevtk_branch
    branch = strip(get(ENV, "BCUBEVTK_BRANCH", "main"))
    @info "Running tests with custom BcubeVTK branch '$branch'"
    branch
else
    nothing
end

SRC_DIR = joinpath(@__DIR__, "..", "src")
names = (
    "constrained_poisson",
    "covo",
    "euler_naca_steady",
    "heat_equation",
    "heat_equation_sphere",
    "heat_equation_two_layers",
    "helmholtz",
    "incompressible_navier_stokes",
    "linear_elasticity",
    "linear_thermoelasticity",
    "linear_transport",
    "phase_field_supercooled",
    "poisson_dg",
    "shallow_water",
    "stokes_flow",
    "transport_hypersurface",
    "transport_supg",
)

@testset "BcubeTutorials" begin
    for name in names
        filename = name * ".jl"
        dir = joinpath(SRC_DIR, name)
        tmp_filepath = joinpath(dir, "tester.jl")
        filepath = joinpath(dir, filename)
        results_path = joinpath(dir, "results.csv")

        # Rq: use of `repr` to ensure path are OK on Windows (otherwise \\ are escaped)
        text = """
# This file is automatically generated
module Tester
using Test
using Pkg
using ReferenceTests
using SparseArrays
using LinearAlgebra

include($(repr(UTILS_PATH)))

ENV["TestMode"] = "true"
#ENV["JULIA_PKG_PRECOMPILE_AUTO"] = 0

Pkg.activate($(repr(dir)))
$has_custom_bcube_branch && Pkg.add(Pkg.PackageSpec(; name = "Bcube", rev = $(repr(custom_bcube_branch))))
$has_custom_bcubevtk_branch && Pkg.add(Pkg.PackageSpec(; name = "BcubeVTK", rev = $(repr(custom_bcubevtk_branch))))
Pkg.instantiate(verbose=false)

ts = Test.DefaultTestSet("Tests for $filename")
Test.push_testset(ts)
include($(repr(filepath)))
Test.pop_testset()
results = Test.get_test_counts(ts)

if VERSION < v"1.11"
    # passes, fails, errors, broken, c_passes, c_fails, c_errors, c_broken, duration
    passes = results[1]
    fails = results[2]
    errors = results[3]
    broken = results[4]
else
    passes = results.passes
    errors = results.errors
    fails = results.fails
    broken = results.broken
end

open($(repr(results_path)), "w") do io
    println(io, "passes,errors,fails,broken")
    println(io, passes, ",", errors, ",", fails, ",", broken)
end

end
"""
        open(tmp_filepath, "w") do f
            print(f, text)
        end

        @testset "$name" begin
            # Display
            print_centered_with_hash("Running case $name", 80)

            # Run the julia script
            cmd = `julia --startup-file=no --project=$TEST_DIR $(tmp_filepath)`
            try
                run(cmd)
            catch e
                REMOVE_TMP_FILES && rm(tmp_filepath)
                throw(e)
            end
            REMOVE_TMP_FILES && rm(tmp_filepath)

            # Check the results
            if isfile(results_path)
                lines = readlines(results_path)
                line = split(lines[2], ',')
                passes, errors, fails, broken = parse.(Int, line)

                # Check that at least one test did run
                # So that we can display "Total = 0" if no test are present
                if passes + errors + fails + broken > 0
                    @test errors == fails == broken == 0
                end

                REMOVE_TMP_FILES && rm(results_path)
            else
                error("Missing result file")
            end
        end
    end
end

end
