module BcubeTutorialsTests
using Pkg
using Test

const TEST_DIR = joinpath(@__DIR__)
const UTILS_PATH = joinpath(TEST_DIR, "utils.jl")
const REMOVE_TMP_FILES = true

Pkg.activate(TEST_DIR)
Pkg.instantiate()

has_custom_bcube_branch = haskey(ENV, "BCUBE_BRANCH")
bcubeSpec = if has_custom_bcube_branch
    branch = get(ENV, "BCUBE_BRANCH")
    @info "Running tests with custom Bcube branch '$branch'"
    Pkg.PackageSpec(; name = "Bcube", rev = branch)
else
    nothing
end

SRC_DIR = joinpath(@__DIR__, "..", "src")
names = (
    "constrained_poisson",
    "covo",
    "euler_naca_steady",
    "heat_equation",
    "heat_equation_sphere",
    "heat_equation_two_layers",
    "helmholtz",
    "incompressible_navier_stokes",
    "linear_elasticity",
    "linear_thermoelasticity",
    "linear_transport",
    "phase_field_supercooled",
    "poisson_dg",
    "shallow_water",
    "stokes_flow",
    "transport_hypersurface",
    "transport_supg",
)

@testset "BcubeTutorials" begin
    for name in names
        filename = name * ".jl"
        dir = joinpath(SRC_DIR, name)
        tmp_filepath = joinpath(dir, "tester.jl")
        filepath = joinpath(dir, filename)
        results_path = joinpath(dir, "results.csv")

        # Rq: use of `repr` to ensure path are OK on Windows (otherwise \\ are escaped)
        text = """
# This file is automatically generated
module Tester
using Test
using Pkg
using ReferenceTests
using SparseArrays

include($(repr(UTILS_PATH)))

ENV["TestMode"] = "true"
#ENV["JULIA_PKG_PRECOMPILE_AUTO"] = 0

Pkg.activate($(repr(dir)))
$has_custom_bcube_branch && Pkg.add(bcubeSpec)
Pkg.instantiate()

ts = Test.DefaultTestSet("Tests for $filename")
Test.push_testset(ts)
include($(repr(filepath)))
Test.pop_testset()
results = Test.get_test_counts(ts)

passes = results.passes
errors = results.errors
fails = results.fails
broken = results.broken

open($(repr(results_path)), "w") do io
    println(io, "passes,errors,fails,broken")
    println(io, passes, ",", errors, ",", fails, ",", broken)
end

end
"""
        open(tmp_filepath, "w") do f
            print(f, text)
        end

        @testset "$name" begin
            # Run the julia script
            cmd = `julia --startup-file=no --project=$TEST_DIR $(tmp_filepath)`
            try
                run(cmd)
            catch e
                REMOVE_TMP_FILES && rm(tmp_filepath)
                throw(e)
            end
            REMOVE_TMP_FILES && rm(tmp_filepath)

            # Check the results
            if isfile(results_path)
                lines = readlines(results_path)
                line = split(lines[2], ',')
                passes, errors, fails, broken = parse.(Int, line)

                # Check that at least one test did run
                # So that we can display "Total = 0" if no test are present
                if passes + errors + fails + broken > 0
                    @test errors == fails == broken == 0
                end

                REMOVE_TMP_FILES && rm(results_path)
            else
                error("Missing result file")
            end
        end
    end
end

end
