# Configuration file for code formatting
# see here for default options : https://github.com/domluna/JuliaFormatter.jl#formatting-options

always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
short_to_long_function_def = true
long_to_short_function_def = false
# always_use_return = true
whitespace_in_kwargs = true
format_docstrings = false
conditional_to_if = true
trailing_comma = true
normalize_line_endings = "unix"
join_lines_based_on_source = false
separate_kwargs_with_semicolon = true
align_assignment = true
align_struct_field = true
align_conditional = true
# align_pair_arrow = true
# align_matrix = true
# format_markdown = true


# possible style : sciml, blue, yas

# ### SciML options
# whitespace_ops_in_indices = true
# remove_extra_newlines = true
# always_for_in = true
# whitespace_typedefs = true
# normalize_line_endings = "unix"

# ### YAS options
# always_for_in = true
# whitespace_ops_in_indices = true
# remove_extra_newlines = true
# import_to_using = true
# pipe_to_function_call = true
# short_to_long_function_def = true
# always_use_return = true
# whitespace_in_kwargs = false
# join_lines_based_on_source = true
# separate_kwargs_with_semicolon = true

# ### Blue option
# always_use_return = true
# short_to_long_function_def = true
# whitespace_ops_in_indices = true
# remove_extra_newlines = true
# always_for_in = true
# import_to_using = true
# pipe_to_function_call = true
# whitespace_in_kwargs = false
# annotate_untyped_fields_with_any = false
# separate_kwargs_with_semicolon = true