# This file is automatically generated
module Tester
using Test
using Pkg
using ReferenceTests
using SparseArrays

include("/d/mbouyges/julia-workspace/BcubeTutorials.jl/test/utils.jl")

ENV["TestMode"] = "true"
#ENV["JULIA_PKG_PRECOMPILE_AUTO"] = 0

Pkg.activate("/d/mbouyges/julia-workspace/BcubeTutorials.jl/test/../src/heat_equation_sphere")
false && Pkg.add(bcubeSpec)
Pkg.instantiate()

ts = Test.DefaultTestSet("Tests for heat_equation_sphere.jl")
Test.push_testset(ts)
include("/d/mbouyges/julia-workspace/BcubeTutorials.jl/test/../src/heat_equation_sphere/heat_equation_sphere.jl")
Test.pop_testset()
results = Test.get_test_counts(ts)

passes = results.passes
errors = results.errors
fails = results.fails
broken = results.broken

open("/d/mbouyges/julia-workspace/BcubeTutorials.jl/test/../src/heat_equation_sphere/results.csv", "w") do io
    println(io, "passes,errors,fails,broken")
    println(io, passes, ",", errors, ",", fails, ",", broken)
end

end
