name: Documentation

on:
  push:
    branches:
      - main
    tags: "*"
  pull_request:
    types: [unlabeled, opened, synchronize, reopened]
  workflow_dispatch:

# Only trigger the job when `draft` label is not assigned to the PR
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'draft') == false
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: "1.9"
      - name: Add Bcube as a global dependency
        run: julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/bcube-project/Bcube.jl"))'
      - name: Set up env
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl
